# Generated by Django 4.2 on 2024-09-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='month',
            name='water_meter',
        ),
        migrations.AddField(
            model_name='month',
            name='water_meter',
            field=models.ManyToManyField(related_name='month', to='utilities.watermeter', verbose_name='Счетчик'),
        ),
    ]
